#
# Path to Android SDK root directory. Nowadays part of Android Studio.
#
# https://developer.android.com/studio
#
SDK_PATH?=$(HOME)/Library/Android/sdk

#
# Path to Android NDK root directory.
#
# https://developer.android.com/ndk/downloads
#
NDK_PATH?=/opt/android-ndk-r21e

#
# Path to Java compiler.
#
JAVAC?=/usr/bin/javac

#
# Path to Google Protocol Buffers compiler. Download precompiled binaries from
# the following GitHub URL:
#
# https://github.com/protocolbuffers/protobuf/releases/
#
# Direct link to 3.15.8, which was used during development:
#
# https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protobuf-java-3.15.8.tar.gz
#
PROTOC?=/opt/bin/protoc

#
# Path to Google Protocol Buffers JAR. Download a precompiled distribution from
# the following URL, but make sure its version matches that of PROTOC specified
# above.
#
# https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java
#
# Direct link to 3.15.8, which was used during development:
#
# https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.15.8/protobuf-java-3.15.8.jar
#
PROTOBUF_JAR?=/tmp/protobuf-java-3.15.8.jar

